apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    containers:
    - name: nginx
      image: nginx:1.18.0
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: "50m"
          memory: "50Mi"
        limits:
          cpu: "100m"
          memory: "100Mi"
      volumeMounts:
      - name: nginx-conf
        mountPath: /etc/nginx
    - name: nginx2
      image: nginx:1.18.0
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: "50m"
          memory: "50Mi"
        limits:
          cpu: "100m"
          memory: "100Mi"
      volumeMounts:
      - name: nginx-conf
        mountPath: /etc/nginx
    volumes:
    - name: nginx-conf
      configMap:
        name: nginx-configmap