apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-registry
  labels:
    app: admission-registry
spec:
  selector:
    matchLabels:
      app: admission-registry
  template:
    metadata:
      labels:
        app: admission-registry
    spec:
      containers:
        - name: whitelist
          image: pooncheebean/admission-registry:latest
          imagePullPolicy: Always
          args:
            - "-sidecarCfgFile=/etc/webhook/config/sidecarconfig.yaml"
            - "-tlsCertFile=/etc/webhook/certs/tls.crt"
            - "-tlsKeyFile=/etc/webhook/certs/tls.key"
          env:
            - name: WHITELIST_REGISTRIES
              value: "docker.io,gcr.io,pooncheebean"
          ports:
            - containerPort: 443
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-registry-tls
        - name: webhook-config
          configMap:
            name: sidecar-injector-webhook-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: admission-registry
  labels:
    app: admission-registry
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: admission-registry