apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
  - name: com.epam.admission-registry-mutate
    clientConfig:
      service:
        name: admission-registry
        namespace: default
        path: "/mutate"
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVRGpzdllqbTJi
        eG9uODRvbFF2c3VDQVlIUGowd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNR
        MDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtC
        Z05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxj
        bTVsZEdWek1CNFhEVEl4TURrd016QTBOVEF3TUZvWERUSTJNRGt3TWpBME5UQXdNRm93WlRFTE1B
        a0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFV
        cHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZR
        UURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNn
        S0NBUUVBczlUQ0pvV1VNU3FmQ3hacTFrUlUKSnhGRzFIbUZyeFdYd1BON3ZDS0hLTy81eWpBZUw4
        NVhDclRyT3BsYXBtMzBNUUJrMit0NHNSVFUyTTMxcGFwOQo0MzZZYTZUWjg4c2lzb1R1YXdNSU1Z
        dXFtcml4TThSOTN5Mjl3ODIxaU8wamxXM1FLemhZeUovaDh1MXhlb1B1CkdqQjN0MTA1ZjZVcmN1
        UEFTMStEOXVBZVZwaXl3alY2Yml0bEV0Zkdld1ZQS1QrcUpQVWdCVGVkM05xYTdnUEwKRHhSVEE1
        bXJXQ2EybExyRnBlWWhBRlI5TXVkeTRmcXRqekRycTlsUWtxN1hMWFZyU1c2K2R6N2R2TTQwdWRB
        RAp6Q1d1cXBBdEFNVjR0NVBGUTI4RFZlblZFQVAzQWQrOFpKczdWME5wWDViem9rN29CMVFkc1Fr
        VSthMWZZbWdrCktRSURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFI
        L0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVTVdpVWNUWVBib2xLdzR0VkRrNHZxK0dMNzcw
        d0h3WURWUjBqQkJnd0ZvQVVNV2lVY1RZUApib2xLdzR0VkRrNHZxK0dMNzcwd0RRWUpLb1pJaHZj
        TkFRRUxCUUFEZ2dFQkFHSG9jT0g2Q0ljL0I2VDM0RVl1CkcxZ1dpL0lRSlI1dkpkVU9kNG9sT3FH
        SGxBeWhoUE8xOXR0aFRBeTI4cGtiVjlheDNjMUtINDhoQkIzcjg0ZmcKODZzcXZ1SFlYbnkwMWs1
        WkpxQW5uREt0b2hBYXBTQ3JiY0lFNkVxN0FRN3grWUxzR0NvSVpxemhIcThxeHFsUQpUMEtiMG9n
        d010L1FsbksxcXRnSFVzNkVXYXRlaEJ0ZmVmMDgrcXoxVmZ1UVJuMDl4R1hLNnRzblBQakJkZzhY
        CmNqbkEvaEZsSTZ0UFRkWWs0dGdXUUpKR2JER0QzaGpBNlhPdFlaTFdLbnplTjdLQStzMmh4VnlF
        Sm1TS3p3UVQKd2RmV0ZCVmRLUThEL21WYnh6OHhmWFpoak1WdmoxZTV0SVNPRmJ2cVpZN1hrcisx
        MUsvUHB1ckxIay9jbGZjMApQUHM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","statefulsets"]
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    namespaceSelector:
      matchLabels:
        sidecar-injection: enabled
