apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
  - name: com.epam.admission-registry-mutate
    clientConfig:
      service:
        name: admission-registry
        namespace: default
        path: "/mutate"
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVWnVEV2xxWWZN
        KzIrWWVjYU1nVkRJdi9ha1Awd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNR
        MDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtC
        Z05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxj
        bTVsZEdWek1CNFhEVEl4TURrd016QTBNRGt3TUZvWERUSTJNRGt3TWpBME1Ea3dNRm93WlRFTE1B
        a0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFV
        cHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZR
        UURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNn
        S0NBUUVBdllmOFQ4aHZQWk03VGwrNDJhYmwKS3lRdmQ4VlcyRXIxWHd4a2lOeWJocjFNV1FYcHNV
        bGdUN3MranBTTkM0Ty9EZlQyWWsrNzFUb1hjZXM3OEFKYgprOW1pZHRZSW8wVlJPNHdVOG81MHcz
        eTgzS3BSTlNPT2JQZWVFL0lnOXI2Y2pyb2txWkdWRWFxN2xlTHVnRENLCmF5cnJ1VTg3YXZvbDQr
        SWJ2WjFYSVR2ejBFcXZxc3owSWpmUnJRbkM3R21teDRNZGdDTUlGeEY2YVhYdDdteFgKK0EvM1RW
        dTlaVUpZOGptb3hZbFlIQ1FoT292VldNWUFkTDh3VkRaMGk4TnZZK3FOUU5hZFBBZkJxajJJZWtM
        MAplMytWbno0UmtNaHY3SnlOc2RRMVBoUko2Z0diWVdTbHBibEoybVk2R0IvWEo1NFRZNWRGMVdU
        c0VMREs3NlpICklRSURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFI
        L0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVSXNaVGpKbktNU0Q3QVlrZU5WTHNTM1l3YWNF
        d0h3WURWUjBqQkJnd0ZvQVVJc1pUakpuSwpNU0Q3QVlrZU5WTHNTM1l3YWNFd0RRWUpLb1pJaHZj
        TkFRRUxCUUFEZ2dFQkFGQVc5OGMrdjFCZnV2UWZ6eitPCjAxTW1MMjBMR2hMSGRUczNqMzB3TkE5
        Y3lTMXRSaW40RE9rU1VtRk9UVTlLYzJVSXJNL3ZSWGwyaGowS053ZmYKdmhTRTkwK1JnRTR4U1Jj
        ZGQwYnlQcTI2WTRlMEhUZkd4Tkc0YmdoaFdvU1dybTJDaUE4NGsvYjRUSVd3ZC9hRAp5UHhMSElj
        aytvaXVvcGFra0szeDRUSlJ0VVc5TFVVSmNpcHN3Ym4wZ1V4YW85WTU4UU9UK21NbTYwZE5PZExu
        CktteW5FVE8xWkVQQmZVT2d0SUxGS0hHaXhKeU1zemxOR0FLWjZRenFMcjc3K3VNME5CUlZEU2NL
        NWtQc3YyWjMKY2M2NzVoc00ydzZJc0djVm4rV2duRlhVUUV6L3ZQNUk0dEx1aXBXdUZFZkZIdlJO
        S0d5UDd6VFh1NlVVQ1FNbApiY0E9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","statefulsets"]
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    namespaceSelector:
      matchLabels:
        sidecar-injection: enabled
