apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
  - name: com.epam.admission-registry-mutate
    clientConfig:
      service:
        name: admission-registry
        namespace: default
        path: "/mutate"
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVZk1ydExUSUds
        SnVLZWZMa29IZ09FNjdCVFlzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNR
        MDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtC
        Z05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxj
        bTVsZEdWek1CNFhEVEl4TURrd016QTBNelV3TUZvWERUSTJNRGt3TWpBME16VXdNRm93WlRFTE1B
        a0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFV
        cHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZR
        UURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNn
        S0NBUUVBcml1MXk3NlI4UFRKTFpnaFFxMEMKUkNPekhWOW54UG44SDRpRlRIajNNWGFiTDFKVmxG
        WENXUDA2bTBNNmQ0Sk1Gc0RTRUtWSGx2Y2NUUE1DbWI1TgpvOXhUNVpYUkI3bFpUd04vNXY1TGtM
        U3oya1B1d0dRSTVQMmNRMWxtSU15UjJOUWpUVVI2ZmlTcmo3ajVjelIxClorZWFyMExNOElMRC9x
        NC9Eb1dNMzhCMW5lUys0R05CMEhlbEZtRVlTZDIyU3BLN0pHZW44VzIrTHFEeFBTUEEKeWQ1OW5q
        dFlSM0VtZVcyOE9Sc01RVlZOY0I4QVRoMGd6TmE5YVhTT0lvUVQ5Z3M4WjRvRVAwdjB4MWxqcmd5
        cQpjdTNuanhuVXIzNDVNU09UdEtZMGk2cWpROGFicE01TlRrak5RSU4yOXBaejhidnI2S3hwWFFZ
        d2RacXZ2UGZ4CldRSURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFI
        L0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVOE5ld2QxMFdKMnZpZ25SbFhiMTZBVWUwWjV3
        d0h3WURWUjBqQkJnd0ZvQVU4TmV3ZDEwVwpKMnZpZ25SbFhiMTZBVWUwWjV3d0RRWUpLb1pJaHZj
        TkFRRUxCUUFEZ2dFQkFBdGhpYXV4T2RJcUJCdVlvVjM3CjIwSmI5TElScmZPaW5CWlFZbXAraHRs
        NXJwWnVOb0ZoK3ZJdks0WDJxeS94SG5jZkhUeGRJUWZuRG95cENja04KUUUvdGhvN1B1OUpUSEln
        Tll6NmEzK3Q3eHExcThlZTY5MHgwTzRCTkpYNUNNWldFNG5qSHVTNnJXN2dlekpXcQpxTzBPcjFw
        WFNOU3lEc2UvKzE4Qkp0RUszWDZFeE5sN1V2SmJsRzY3eCtjcW9mSzlZcE81U1NYdHJFR2lCeVJX
        CkRDV3VlMlJJNlh3WmNCa1ovb1lwazM2TWpWTlYwdWRVenNHSDVGRmdZckV3cnhXSWlmdjBRd1N1
        RURUaENOb24KMEFTdk9lNEtHTlFYb0ROWXB2eWduSjAxVDJDdUh6Z0krb1JTU1ZIeDRBMVFnOS9F
        a3pFUFllMnovMkt0ZlNYTAppQ009Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","statefulsets"]
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    namespaceSelector:
      matchLabels:
        sidecar-injection: enabled
