apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-registry
webhooks:
  - name: com.epam.admission-registry
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
    clientConfig:
      service:
        namespace: default
        name: admission-registry
        path: "/validate"
      #caBundle: CA_BUNDLE （cat ca.pem | base64）
      caBundle: >
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVSFZpQnhwRXlq
        c2tFMDM1L3VEb2UxRzlrSVpJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNR
        MDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtC
        Z05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxj
        bTVsZEdWek1CNFhEVEl4TURjeU5qQTBNREl3TUZvWERUSTJNRGN5TlRBME1ESXdNRm93WlRFTE1B
        a0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFV
        cHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZR
        UURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNn
        S0NBUUVBeVM1cjhGRy9Ucm1JRzlGNFV1aVQKT2RSWU5QVWtDWE9Cb0xocUpMT1R6Ym5vRFFEVVQr
        cjlydVF0RzVnQ3FaVFRBbG1WdDFha243d1k5VW95dUNXcgpzL2lGZnhFdmZPSFE1YUFwU3lNdFVY
        c29pdXFhRDljb25vZzY5L1VGUXRKV1NpbnJLODFVeEhJeHYvNU1wSnZuCk1MVy84bi9pTDlCcXph
        RWg0KzlNYTJ5ckxHNFFrMzhQcXAycC95TGtUbXdndE9Ec0NVM2hlVVMrejk5K2RTTWEKYkdrZHJP
        Z0UxUnRsUmRNL0hPc3ZDZ2NYK1htditRMkcxWmdZV0srYldOV1JzTkVIazV6K0JRK0FFaVNaNXhL
        TQpLcU03Tkx2QldrTnpyMlpwRWd1cVJoTlN1STN5QjVJbkdmQlhBdkNZVlRwbFI3WTE1UDB6aTY5
        bmllUGUxcjhzCjJ3SURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFI
        L0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVZ0tWZ25BTFk0MDRmdXUxZHlQWlc4OHhBUXpV
        d0h3WURWUjBqQkJnd0ZvQVVnS1ZnbkFMWQo0MDRmdXUxZHlQWlc4OHhBUXpVd0RRWUpLb1pJaHZj
        TkFRRUxCUUFEZ2dFQkFIdmJwMW4wYTJTT0pVQWxyNWJFCnVkY01KUG84ZExFWGdtL1RNc2N0My9k
        VkJUSEtxdEtpdnlpWE53TVo5SGViRE5URnMvd2xGYXZ5dE9IWnlHSDEKVHNMaHlmaks5MlJJb01J
        anhEZk9GUmI5OVcwUEFkQ1Q0OW9jdDBUK2hDU2hpeTNoVGdKTDRzZDAvU0ZMa0VKTgpiVFJBUStP
        RzhtNUdRZXpiUDEyY1JyMWlOVFBGdUNBcG5XYVk0dVJkM3JkNm5MQkcrengra1dleTJ4MzQxYXE3
        ClJSaDRYSGZGTm9nd2RMYWZnN1l3cjNhVndDMEszY0Q2aCt2MlJxRnhvWnl5RVlHZ2RPS1lBUXU3
        cWlzNTM4dnoKT0FnTTcvZEdEUC9zZmZ3ekxxMDl5WTRpcVVvTFU1bmlYcXRGVDdxaEpDOUtPYyts
        UUgxZzNqRFBDQWJHVTFlcQphL3c9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None